export const LANDING_VIDEOS = [
  {
    id: "YC87WmFN_As",
    title: "Starship Flight 5 Booster Catch",
    channel: "SpaceX",
    type: "Mechazilla Catch",
    booster: "B12 Super Heavy",
    vehicle: "Starship",
    mission: "Flight 5",
    date: "2024-10-13",
    success: true,
    pad: "Launch Mount - Starbase, TX",
    weather: "Clear, wind 4 km/h",
    featured: true,
    landingType: "Mechazilla Tower Catch",
    timeline: [
      { id: "ascent", label: "Ascent Profile", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Hot-Stage Separation", status: "Nominal", time: "T+ 2:42" },
      { id: "boostback", label: "Boostback Burn", status: "Nominal", time: "T+ 3:05" },
      { id: "entry_burn", label: "Entry Burn", status: "Nominal", time: "T+ 6:40" },
      { id: "landing_burn", label: "Landing Burn Init", status: "Nominal", time: "T+ 7:31" },
      { id: "touchdown", label: "Super Heavy Tower Capture", status: "Nominal", time: "T+ 7:45" }
    ]
  },
  {
    id: "LHqLz9ni0Bo",
    title: "Falcon 9 Onboard Droneship Landing",
    channel: "SpaceX",
    type: "Onboard Droneship",
    booster: "B1046 Block 5",
    vehicle: "Falcon 9",
    mission: "Telstar 19V",
    date: "2018-07-22",
    success: true,
    pad: "Of Course I Still Love You (ASDS)",
    weather: "Moderate swells, misty",
    featured: false,
    landingType: "ASDS Sea Landing",
    timeline: [
      { id: "ascent", label: "Liftoff & Ascent", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Stage Separation", status: "Nominal", time: "T+ 2:33" },
      { id: "boostback", label: "No Boostback (Downrange)", status: "Skipped", time: "N/A" },
      { id: "entry_burn", label: "Entry Burn Execution", status: "Nominal", time: "T+ 6:15" },
      { id: "landing_burn", label: "Single Engine Landing Burn", status: "Nominal", time: "T+ 8:08" },
      { id: "touchdown", label: "ASDS Deck Touchdown", status: "Nominal", time: "T+ 8:31" }
    ]
  },
  {
    id: "lXgLyCYuYA4",
    title: "CRS-8: First Successful Sea Landing",
    channel: "SpaceX",
    type: "Historic Droneship",
    booster: "B1021.1",
    vehicle: "Falcon 9",
    mission: "CRS-8",
    date: "2016-04-08",
    success: true,
    pad: "Of Course I Still Love You (ASDS)",
    weather: "Calm sea swell, light breeze",
    featured: false,
    landingType: "ASDS Sea Landing",
    timeline: [
      { id: "ascent", label: "Ascent Profile", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Stage Separation", status: "Nominal", time: "T+ 2:30" },
      { id: "boostback", label: "Partial Boostback", status: "Nominal", time: "T+ 2:45" },
      { id: "entry_burn", label: "Atmospheric Entry Burn", status: "Nominal", time: "T+ 6:45" },
      { id: "landing_burn", label: "Landing Burn Init", status: "Nominal", time: "T+ 8:12" },
      { id: "touchdown", label: "Historic ASDS Touchdown", status: "Nominal", time: "T+ 8:35" }
    ]
  },
  {
    id: "Z4TXCZG_NEY",
    title: "Falcon Heavy Test Flight Dual Landing",
    channel: "SpaceX",
    type: "LZ-1 & LZ-2",
    booster: "B1023.1 & B1025.1",
    vehicle: "Falcon Heavy",
    mission: "Demo Flight",
    date: "2018-02-06",
    success: true,
    pad: "Landing Zone 1 & 2 (Ground)",
    weather: "Optimal, light crosswinds",
    featured: true,
    landingType: "RTLS Ground landing",
    timeline: [
      { id: "ascent", label: "Ascent Profile", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Dual Booster Separation", status: "Nominal", time: "T+ 2:33" },
      { id: "boostback", label: "Dual Boostback Burn", status: "Nominal", time: "T+ 3:11" },
      { id: "entry_burn", label: "Dual Entry Burn", status: "Nominal", time: "T+ 6:42" },
      { id: "landing_burn", label: "Dual Landing Burn", status: "Nominal", time: "T+ 7:58" },
      { id: "touchdown", label: "Synchronized Ground Landing", status: "Nominal", time: "T+ 8:15" }
    ]
  },
  {
    id: "wbSwFU6tY1c",
    title: "Falcon 9 First Stage LZ-1 Landing",
    channel: "SpaceX",
    type: "Historic LZ-1",
    booster: "B1019.1",
    vehicle: "Falcon 9",
    mission: "Orbcomm-2",
    date: "2015-12-21",
    success: true,
    pad: "Landing Zone 1 - Cape Canaveral",
    weather: "Clear, pristine nighttime",
    featured: false,
    landingType: "RTLS Ground landing",
    timeline: [
      { id: "ascent", label: "Liftoff & Ascent", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Stage Separation", status: "Nominal", time: "T+ 2:24" },
      { id: "boostback", label: "Full Boostback Burn", status: "Nominal", time: "T+ 2:48" },
      { id: "entry_burn", label: "Atmospheric Entry Burn", status: "Nominal", time: "T+ 8:00" },
      { id: "landing_burn", label: "Landing Burn Init", status: "Nominal", time: "T+ 9:32" },
      { id: "touchdown", label: "Historic Ground Touchdown", status: "Nominal", time: "T+ 9:44" }
    ]
  },
  {
    id: "1_FXVjqZIQM",
    title: "SAOCOM 1A West Coast Landing",
    channel: "SpaceX",
    type: "LZ-4 Landing",
    booster: "B1048.1",
    vehicle: "Falcon 9",
    mission: "SAOCOM 1A",
    date: "2018-10-08",
    success: true,
    pad: "Landing Zone 4 - Vandenberg",
    weather: "Mild fog, low visibility",
    featured: false,
    landingType: "RTLS Ground landing",
    timeline: [
      { id: "ascent", label: "Ascent Profile", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Stage Separation", status: "Nominal", time: "T+ 2:20" },
      { id: "boostback", label: "RTLS Boostback", status: "Nominal", time: "T+ 2:38" },
      { id: "entry_burn", label: "Atmospheric Entry Burn", status: "Nominal", time: "T+ 6:02" },
      { id: "landing_burn", label: "Center-Engine Landing Burn", status: "Nominal", time: "T+ 7:38" },
      { id: "touchdown", label: "Vandenberg Ground Touchdown", status: "Nominal", time: "T+ 7:45" }
    ]
  },
  {
    id: "OnoNITE-clc",
    title: "Falcon 9 Transporter-2 Landing",
    channel: "SpaceX",
    type: "LZ-1 Landing",
    booster: "B1060.8",
    vehicle: "Falcon 9",
    mission: "Transporter-2",
    date: "2021-06-30",
    success: true,
    pad: "Landing Zone 1 - Cape Canaveral",
    weather: "Scattered clouds, humid",
    featured: false,
    landingType: "RTLS Ground landing",
    timeline: [
      { id: "ascent", label: "Ascent Profile", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Stage Separation", status: "Nominal", time: "T+ 2:28" },
      { id: "boostback", label: "Boostback Burn", status: "Nominal", time: "T+ 2:44" },
      { id: "entry_burn", label: "Atmospheric Entry", status: "Nominal", time: "T+ 6:21" },
      { id: "landing_burn", label: "Propulsive Deceleration", status: "Nominal", time: "T+ 7:51" },
      { id: "touchdown", label: "LZ-1 Ground Touchdown", status: "Nominal", time: "T+ 8:04" }
    ]
  },
  {
    id: "sB_nEtZxPOA",
    title: "Starship SN15 High-Altitude Landing",
    channel: "SpaceX",
    type: "Starship Landing",
    booster: "SN15 Upper Stage",
    vehicle: "Starship",
    mission: "SN15 Test Flight",
    date: "2021-05-05",
    success: true,
    pad: "Starbase Landing Pad, TX",
    weather: "Breezy gulf winds",
    featured: false,
    landingType: "Starbase Pad Ground touchdown",
    timeline: [
      { id: "ascent", label: "Raptor Powered Ascent", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Sequential Engine Cutdowns", status: "Nominal", time: "T+ 4:15" },
      { id: "boostback", label: "Bellyflop Descent Control", status: "Nominal", time: "T+ 5:20" },
      { id: "entry_burn", label: "Aerodynamic Maneuver", status: "Nominal", time: "T+ 5:45" },
      { id: "landing_burn", label: "Raptor Flip-up & Gimbals", status: "Nominal", time: "T+ 5:58" },
      { id: "touchdown", label: "Touchdown and Venting", status: "Nominal", time: "T+ 6:08" }
    ]
  },
  {
    id: "bvim4rsNHkQ",
    title: "Falcon Heavy Arabsat-6A Landing",
    channel: "SpaceX",
    type: "LZ-1 & LZ-2",
    booster: "B1052 & B1053 Side Boosters",
    vehicle: "Falcon Heavy",
    mission: "Arabsat-6A",
    date: "2019-04-11",
    success: true,
    pad: "Landing Zone 1 & 2 (Ground)",
    weather: "Cool, crystal clear night",
    featured: false,
    landingType: "RTLS Ground landing",
    timeline: [
      { id: "ascent", label: "Maximum Dynamic Pressure", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Dual Booster Separation", status: "Nominal", time: "T+ 2:38" },
      { id: "boostback", label: "Synchronized Boostback Burn", status: "Nominal", time: "T+ 3:20" },
      { id: "entry_burn", label: "Booster Atmospheric Entry", status: "Nominal", time: "T+ 6:48" },
      { id: "landing_burn", label: "Parallel Ground Land Burn", status: "Nominal", time: "T+ 8:02" },
      { id: "touchdown", label: "Perfect Dual Touchdown", status: "Nominal", time: "T+ 8:17" }
    ]
  },
  {
    id: "pYHQCxXIt3M",
    title: "Starship Flight 6 Super Heavy Catch",
    channel: "SpaceX",
    type: "Mechazilla Catch",
    booster: "B13 Super Heavy",
    vehicle: "Starship",
    mission: "Flight 6",
    date: "2024-11-19",
    success: false,
    pad: "Gulf of Mexico (Water Soft Catch)",
    weather: "Sunset, overcast, choppy waters",
    featured: false,
    landingType: "Water Catch (Catch Abort)",
    timeline: [
      { id: "ascent", label: "Super Heavy Ascent Boost", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Hot-Stage Separation", status: "Nominal", time: "T+ 2:40" },
      { id: "boostback", label: "Boostback Burn", status: "Nominal", time: "T+ 2:50" },
      { id: "entry_burn", label: "Entry Burn Segment", status: "Nominal", time: "T+ 6:23" },
      { id: "landing_burn", label: "Booster Catch Abort Decided", status: "Aborted", time: "T+ 7:00" },
      { id: "touchdown", label: "Indian Ocean Soft Splashdown", status: "Loss of Booster", time: "T+ 7:15" }
    ]
  },
  {
    id: "A0FZIwabctw",
    title: "Falcon 9 NROL-108 Landing",
    channel: "SpaceX",
    type: "LZ-1 Landing",
    booster: "B1059.5",
    vehicle: "Falcon 9",
    mission: "NROL-108",
    date: "2020-12-19",
    success: true,
    pad: "Landing Zone 1 - Cape Canaveral",
    weather: "Windy, heavy overcast",
    featured: false,
    landingType: "RTLS Ground landing",
    timeline: [
      { id: "ascent", label: "Asymmetrical Ascent", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Stage Separation", status: "Nominal", time: "T+ 2:18" },
      { id: "boostback", label: "RTLS Boostback", status: "Nominal", time: "T+ 2:32" },
      { id: "entry_burn", label: "Re-entry Burn Profile", status: "Nominal", time: "T+ 5:54" },
      { id: "landing_burn", label: "Single Engine Landing", status: "Nominal", time: "T+ 8:05" },
      { id: "touchdown", label: "LZ-1 Ground Touchdown", status: "Nominal", time: "T+ 8:15" }
    ]
  },
  {
    id: "C3b2ZqS3X8Y",
    title: "Falcon 9 Crew-1 Landing",
    channel: "SpaceX",
    type: "Droneship Catch",
    booster: "B1061.1",
    vehicle: "Falcon 9",
    mission: "Crew-1",
    date: "2020-11-15",
    success: true,
    pad: "Just Read the Instructions (ASDS)",
    weather: "Breezy night sea state",
    featured: false,
    landingType: "ASDS Sea Landing",
    timeline: [
      { id: "ascent", label: "Manned Ascent Profile", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Stage Separation", status: "Nominal", time: "T+ 2:36" },
      { id: "boostback", label: "Downrange Descent Coast", status: "Skipped", time: "N/A" },
      { id: "entry_burn", label: "Atmospheric Re-entry", status: "Nominal", time: "T+ 6:30" },
      { id: "landing_burn", label: "Plume Interaction Burn", status: "Nominal", time: "T+ 8:43" },
      { id: "touchdown", label: "Night Droneship Touchdown", status: "Nominal", time: "T+ 9:02" }
    ]
  },
  {
    id: "7v4k22WpWvo",
    title: "Falcon 9 GPS III SV04 Landing",
    channel: "SpaceX",
    type: "Droneship Catch",
    booster: "B1062.1",
    vehicle: "Falcon 9",
    mission: "GPS III SV04",
    date: "2020-11-05",
    success: true,
    pad: "Of Course I Still Love You (ASDS)",
    weather: "Overcast, slight waves",
    featured: false,
    landingType: "ASDS Sea Landing",
    timeline: [
      { id: "ascent", label: "High Energy Ascent", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Stage Separation", status: "Nominal", time: "T+ 2:42" },
      { id: "boostback", label: "Ascent Coast", status: "Skipped", time: "N/A" },
      { id: "entry_burn", label: "Dense Entry Burn", status: "Nominal", time: "T+ 6:41" },
      { id: "landing_burn", label: "Gimbal Ring Correction", status: "Nominal", time: "T+ 8:14" },
      { id: "touchdown", label: "Precision Sea Landing", status: "Nominal", time: "T+ 8:36" }
    ]
  },
  {
    id: "0a_00nJ_Y88",
    title: "Starship Flight 4 Splashdown",
    channel: "SpaceX",
    type: "Ocean Splashdown",
    booster: "B11 Super Heavy",
    vehicle: "Starship",
    mission: "Flight 4",
    date: "2024-06-06",
    success: true,
    pad: "Gulf of Mexico (Virtual Pad)",
    weather: "Heavy fog, clear waves",
    featured: false,
    landingType: "Soft Sea-Contact Splashdown",
    timeline: [
      { id: "ascent", label: "Super Heavy Booster Launch", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Hot-Staging Cutover", status: "Nominal", time: "T+ 2:40" },
      { id: "boostback", label: "Booster Boostback Burn", status: "Nominal", time: "T+ 3:12" },
      { id: "entry_burn", label: "Booster Entry Burn", status: "Nominal", time: "T+ 6:43" },
      { id: "landing_burn", label: "Trans-Landing Burn", status: "Nominal", time: "T+ 7:22" },
      { id: "touchdown", label: "Precision Hover Splashdown", status: "Nominal", time: "T+ 7:31" }
    ]
  },
  {
    id: "xYWzF_1d7A8",
    title: "Falcon 9 Sentinel-6 Michael Freilich Landing",
    channel: "SpaceX",
    type: "Vandenberg LZ-4",
    booster: "B1063.1",
    vehicle: "Falcon 9",
    mission: "Sentinel-6",
    date: "2020-11-21",
    success: true,
    pad: "Landing Zone 4 - Vandenberg SFB",
    weather: "Clear, pristine coastal winds",
    featured: false,
    landingType: "RTLS Ground landing",
    timeline: [
      { id: "ascent", label: "Pacific Orbit Path", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Inertial Separation", status: "Nominal", time: "T+ 2:24" },
      { id: "boostback", label: "Propulsive Reverse Burn", status: "Nominal", time: "T+ 2:45" },
      { id: "entry_burn", label: "Braking Core Burn", status: "Nominal", time: "T+ 6:13" },
      { id: "landing_burn", label: "Final Gravity Descent", status: "Nominal", time: "T+ 8:12" },
      { id: "touchdown", label: "LZ-4 Ground Touchdown", status: "Nominal", time: "T+ 8:27" }
    ]
  },
  {
    id: "_T74T7yPIfc",
    title: "Falcon Heavy USSF-44 Dual Landing",
    channel: "SpaceX",
    type: "LZ-1 & LZ-2",
    booster: "B1064 & B1065 Side Boosters",
    vehicle: "Falcon Heavy",
    mission: "USSF-44",
    date: "2022-11-01",
    success: true,
    pad: "Landing Zone 1 & 2 (Ground)",
    weather: "Overcast, slight tailwinds",
    featured: false,
    landingType: "RTLS Ground landing",
    timeline: [
      { id: "ascent", label: "Classified Profile Ascent", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Dual Booster Separation", status: "Nominal", time: "T+ 2:30" },
      { id: "boostback", label: "Dual Booster RTLS Ignite", status: "Nominal", time: "T+ 3:00" },
      { id: "entry_burn", label: "Simultaneous Core Braking", status: "Nominal", time: "T+ 6:35" },
      { id: "landing_burn", label: "Dual 3-Engine Retardation", status: "Nominal", time: "T+ 8:05" },
      { id: "touchdown", label: "Simultaneous LZ Touchdown", status: "Nominal", time: "T+ 8:22" }
    ]
  },
  {
    id: "ru1A11lmbA4",
    title: "Falcon 9 Iridium-1 Landing",
    channel: "SpaceX",
    type: "West Coast LZ",
    booster: "B1029.2",
    vehicle: "Falcon 9",
    mission: "Iridium-1",
    date: "2017-01-14",
    success: true,
    pad: "Just Read the Instructions (ASDS)",
    weather: "Heavy fog, medium waves",
    featured: false,
    landingType: "ASDS Sea Landing",
    timeline: [
      { id: "ascent", label: "Polar Route Liftoff", status: "Nominal", time: "T+ 0:00" },
      { id: "stage_sep", label: "Pristine Stage Separation", status: "Nominal", time: "T+ 2:27" },
      { id: "boostback", label: "Downrange Drift Phase", status: "Skipped", time: "N/A" },
      { id: "entry_burn", label: "Core Plume Braking", status: "Nominal", time: "T+ 6:21" },
      { id: "landing_burn", label: "Center-Engine Capture Spark", status: "Nominal", time: "T+ 8:14" },
      { id: "touchdown", label: "Pacific ASDS Sea Touchdown", status: "Nominal", time: "T+ 8:26" }
    ]
  }
];

export const SPACEX_HISTORIC_EVENTS = [
  {
    id: "hist-starship-flight12",
    title: "Starship Flight 12 Dual Catch",
    date: "May 10, 2026",
    dateUtc: "2026-05-10T13:40:00.000Z",
    video_id: "YC87WmFN_As",
    vehicle: "Starship & Super Heavy V2",
    launchpad: "Starbase OLP-1, Boca Chica, TX",
    details: "Demonstrating full rapid reusability, Flight 12 achieved the unprecedented milestone of catching both the Super Heavy booster and the Starship upper stage back at the launch mount.",
    coreSerial: "B20 Booster & S36 Ship",
    flightNum: 2,
    reused: true,
    landingType: "Mechazilla Tower Catch"
  },
  {
    id: "hist-starship-flight11",
    title: "Starship Flight 11 Orbital Transfer",
    date: "Feb 22, 2026",
    dateUtc: "2026-02-22T14:00:00.000Z",
    video_id: "pYHQCxXIt3M",
    vehicle: "Starship & Super Heavy V2",
    launchpad: "Starbase OLP-1, Boca Chica, TX",
    details: "Flight 11 marked a major step towards Artemis by completing an orbital propellant transfer demonstration between Starship and a target vehicle.",
    coreSerial: "B18 Booster & S33 Ship",
    flightNum: 1,
    reused: false,
    landingType: "Mechazilla Tower Catch"
  },
  {
    id: "hist-starship-flight10",
    title: "Starship Flight 10 Payload Deployment",
    date: "Nov 30, 2025",
    dateUtc: "2025-11-30T13:15:00.000Z",
    video_id: "0a_00nJ_Y88",
    vehicle: "Starship & Super Heavy V1",
    launchpad: "Starbase OLP-1, Boca Chica, TX",
    details: "Flight 10 successfully opened its payload bay door in orbit, deploying the first batch of full-scale Starlink V2 satellites before re-entering the atmosphere.",
    coreSerial: "B17 Booster & S31 Ship",
    flightNum: 2,
    reused: true,
    landingType: "Mechazilla Tower Catch"
  },
  {
    id: "hist-starship-flight9",
    title: "Starship Flight 9 Dual Ship Catch Attempt",
    date: "Aug 15, 2025",
    dateUtc: "2025-08-15T12:00:00.000Z",
    video_id: "YC87WmFN_As",
    vehicle: "Starship & Super Heavy V1",
    launchpad: "Starbase OLP-1, Boca Chica, TX",
    details: "Flight 9 featured a full orbital profile and the first attempt to catch the Starship upper stage, paving the way for complete rapid reusability.",
    coreSerial: "B16 Booster & S30 Ship",
    flightNum: 1,
    reused: false,
    landingType: "Mechazilla Tower Catch"
  },
  {
    id: "hist-crew9",
    title: "Crew-9: ISS Expedition 72/73",
    date: "Sep 28, 2024",
    dateUtc: "2024-09-28T17:17:00.000Z",
    video_id: "7B_Wty9r4p4",
    vehicle: "Falcon 9 Block 5 (Crew Dragon Freedom)",
    launchpad: "SLC-40, Cape Canaveral, FL",
    details: "Crew-9 launched to the International Space Station, notable for launching from SLC-40 for the first time for a crewed mission and returning two Starliner astronauts.",
    coreSerial: "B1085",
    flightNum: 2,
    reused: true,
    landingType: "LZ-1 Ground Landing"
  },
  {
    id: "hist-polaris-dawn",
    title: "Polaris Dawn: First Commercial Spacewalk",
    date: "Sep 12, 2024",
    dateUtc: "2024-09-12T10:12:00.000Z",
    video_id: "7B_Wty9r4p4",
    vehicle: "Falcon 9 Block 5 (Crew Dragon Resilience)",
    launchpad: "LC-39A, Kennedy Space Center, FL",
    details: "The Polaris Dawn mission achieved the highest Earth orbit since the Apollo program and conducted the first-ever commercial Extravehicular Activity (EVA), using newly designed SpaceX EVA suits.",
    coreSerial: "B1083",
    flightNum: 4,
    reused: true,
    landingType: "Just Read the Instructions"
  },
  {
    id: "hist-crew8",
    title: "Crew-8: ISS Expedition 71",
    date: "Mar 3, 2024",
    dateUtc: "2024-03-03T03:53:00.000Z",
    video_id: "bnqqOBrPucA",
    vehicle: "Falcon 9 Block 5 (Crew Dragon Endeavour)",
    launchpad: "LC-39A, Kennedy Space Center, FL",
    details: "Crew-8 carried four astronauts to the International Space Station for a six-month science mission, marking the eighth operational crew flight for NASA.",
    coreSerial: "B1083",
    flightNum: 1,
    reused: false,
    landingType: "LZ-1 Ground Landing"
  },
  {
    id: "hist-starship-flight5",
    title: "Starship Flight 5 Tower Catch",
    date: "Oct 13, 2024",
    dateUtc: "2024-10-13T12:25:00.000Z",
    video_id: "YC87WmFN_As",
    vehicle: "Starship & Super Heavy B12",
    launchpad: "Starbase OLP-1, Boca Chica, TX",
    details: "During the Starship Flight 5 campaign, SpaceX achieved a breathtaking world-first by catching the 232-foot-tall Super Heavy booster back at the launch mount using the tower's 'Mechazilla' chopstick arms.",
    coreSerial: "B12 Booster",
    flightNum: 1,
    reused: false,
    landingType: "Mechazilla Tower Catch"
  },
  {
    id: "hist-crew1",
    title: "Crew-1: First Operational Crew Mission",
    date: "Nov 15, 2020",
    dateUtc: "2020-11-15T00:27:00.000Z",
    video_id: "bnqqOBrPucA",
    vehicle: "Falcon 9 Block 5 (Crew Dragon Resilience)",
    launchpad: "LC-39A, Kennedy Space Center, FL",
    details: "Following the successful Demo-2 test flight, Crew-1 marked the first operational crewed flight of the Dragon spacecraft, carrying four astronauts to the ISS for a full-duration six-month science mission.",
    coreSerial: "B1061",
    flightNum: 1,
    reused: false,
    landingType: "Just Read the Instructions"
  },
  {
    id: "hist-demo2",
    title: "Demo-2 First Crewed Flight",
    date: "May 30, 2020",
    dateUtc: "2020-05-30T19:22:00.000Z",
    video_id: "bZOPV5pU_bY",
    vehicle: "Falcon 9 Block 5 (Crew Dragon)",
    launchpad: "LC-39A, Kennedy Space Center, FL",
    details: "SpaceX successfully launched NASA astronauts Bob Behnken and Doug Hurley on Demo-2, restoring domestic astronaut launch capability to American soil for the first time since the Space Shuttle's retirement in 2011.",
    coreSerial: "B1058",
    flightNum: 1,
    reused: false,
    landingType: "Of Course I Still Love You"
  },
  {
    id: "hist-falconheavy-test",
    title: "Falcon Heavy Maiden Test Flight",
    date: "Feb 6, 2018",
    dateUtc: "2018-02-06T20:45:00.000Z",
    video_id: "Z4TXCZG_NEY",
    vehicle: "Falcon Heavy (B1033 / B1023 / B1025)",
    launchpad: "LC-39A, Kennedy Space Center, FL",
    details: "The highly anticipated inaugural launch of Falcon Heavy lifted Elon Musk's cherry red Tesla Roadster dummy payload into a heliocentric helio-orbit, featuring the famous synchronized dual landing of the side boosters at Landing Zones 1 and 2.",
    coreSerial: "B1023 / B1025 side boosters",
    flightNum: 2,
    reused: true,
    landingType: "LZ-1 & LZ-2 Dual Landing"
  },
  {
    id: "hist-arabsat6a",
    title: "Falcon Heavy: Arabsat-6A Triple Landing",
    date: "Apr 11, 2019",
    dateUtc: "2019-04-11T22:35:00.000Z",
    video_id: "TXMGu2d8c8g",
    vehicle: "Falcon Heavy (B1055/B1052/B1053)",
    launchpad: "LC-39A, Kennedy Space Center, FL",
    details: "The first commercial deployment for Falcon Heavy marked a massive milestone when both side boosters landed successfully at LZ-1 and LZ-2, shortly followed by the center core landing on the drone ship Of Course I Still Love You.",
    coreSerial: "B1055 (Center Core)",
    flightNum: 1,
    reused: false,
    landingType: "LZ-1, LZ-2, and OCISLY Drone Ship"
  },
  {
    id: "hist-sn15-landing",
    title: "Starship SN15 High-Altitude Landing",
    date: "May 5, 2021",
    dateUtc: "2021-05-05T22:24:00.000Z",
    video_id: "sB_nEtZxPOA",
    vehicle: "Starship Prototype SN15",
    launchpad: "Starbase Suborbital Pad A, TX",
    details: "Following several explosive suborbital flight lessons, Starship SN15 successfully launched to 10 km altitude, performed a belly-flop descent maneuver using aerodynamic flaps, and ignited three Raptor engines to achieve a perfect touchdown at Boca Chica.",
    coreSerial: "SN15 Prototype",
    flightNum: 1,
    reused: false,
    landingType: "Starbase Landing Pad"
  },
  {
    id: "hist-orbcomm2",
    title: "Orbcomm-2: First Ever Booster Return",
    date: "Dec 21, 2015",
    dateUtc: "2015-12-21T18:33:00.000Z",
    video_id: "ZCBE8ocOkAQ",
    vehicle: "Falcon 9 v1.1 Full Thrust",
    launchpad: "SLC-40, Cape Canaveral, FL",
    details: "SpaceX accomplished one of the most critical feats in reusable rocketry by returning the Falcon 9 Orbcomm-2 first stage back to earth for a ground landing at Landing Zone 1, verifying full booster reuse economics.",
    coreSerial: "B1019 First Lander",
    flightNum: 1,
    reused: false,
    landingType: "Landing Zone 1 Ground Touchdown"
  },
  {
    id: "hist-crs8",
    title: "CRS-8 First Drone Ship Sea landing",
    date: "Apr 8, 2016",
    dateUtc: "2016-04-08T18:33:00.000Z",
    video_id: "lXgLyCYuYA4",
    vehicle: "Falcon 9 v1.1 FT",
    launchpad: "SLC-40, Cape Canaveral, FL",
    details: "After multiple near-miss attempts, booster B1021 landed upright on the drone ship 'Of Course I Still Love You' during the CRS-8 mission, completing the first successful ocean recovery in history.",
    coreSerial: "B1021",
    flightNum: 1,
    reused: false,
    landingType: "OCISLY Ocean Recovery"
  },
  {
    id: "hist-falcon1-flight4",
    title: "Falcon 1 Flight 4 Maiden Success",
    date: "Sep 28, 2008",
    dateUtc: "2008-09-28T19:15:00.000Z",
    video_id: "dLQ5xgWyX_k",
    vehicle: "Falcon 1 Flight 4",
    launchpad: "Omelek Island, Kwajalein Atoll",
    details: "Facing complete corporate ruin, Elon Musk's small engineering crew successfully launched the fourth Falcon 1 vehicle into a stable orbit, creating the world's first liquid-propellant orbital rocket funded entirely by private enterprise.",
    coreSerial: "Falcon 1 Merlins",
    flightNum: 1,
    reused: false,
    landingType: "No Recovery Attempt (Expended)"
  },
  {
    id: "hist-inspiration4",
    title: "Inspiration4: All-Civilian Spaceflight",
    date: "Sep 15, 2021",
    dateUtc: "2021-09-15T22:02:00.000Z",
    video_id: "3pvDF_o3sc0",
    vehicle: "Falcon 9 Block 5 (Crew Dragon)",
    launchpad: "LC-39A, Kennedy Space Center, FL",
    details: "Inspiration4 flew four civilian crew members on a custom high-altitude orbital vacation without professional government pilots, raising hundreds of millions for pediatric cancer research and proving civilian space accessibility.",
    coreSerial: "B1062",
    flightNum: 3,
    reused: true,
    landingType: "Just Read the Instructions"
  },
  {
    id: "hist-starship-flight4",
    title: "Starship Flight 4 Ocean Splashdown",
    date: "Jun 6, 2024",
    dateUtc: "2024-06-06T12:50:00.000Z",
    video_id: "0a_00nJ_Y88",
    vehicle: "Starship & Super Heavy B11",
    launchpad: "Starbase OLP-1, Boca Chica, TX",
    details: "Starship completed its entire orbital test campaign, surviving severe atmospheric re-entry friction despite significant side flap erosion, and successfully executing a soft horizontal flip and vertical splashdown in the Indian Ocean.",
    coreSerial: "B11 Booster & S29 Ship",
    flightNum: 1,
    reused: false,
    landingType: "Indian Ocean soft sea-contact"
  }
];

export const FALLBACK_UPCOMING = [
  {
    id: "starship-flight-6",
    name: "Starship Flight 6",
    date_utc: "2026-06-18T21:00:00.000Z",
    details: "Sixth test flight of the combined Starship and Super Heavy vehicle, targeting booster catch at Starbase and orbital stage ocean landing.",
    rocket_name: "Starship",
    launchpad_name: "Starbase OLP-1",
    upcoming: true,
    flight_number: 160,
    links: {
      patch: { large: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&q=80&w=400" },
      webcast: "https://www.youtube.com/watch?v=l_g2s8mIWeQ"
    }
  },
  {
    id: "crew-10",
    name: "Crew-10 (USCV-10)",
    date_utc: "2026-07-31T09:12:00.000Z",
    details: "SpaceX Crew-10 mission is scheduled to launch four crew members to the Area Orbit aboard a Crew Dragon spacecraft.",
    rocket_name: "Falcon 9 Block 5",
    launchpad_name: "LC-39A, Kennedy Space Center",
    upcoming: true,
    flight_number: 161,
    links: {
      patch: { large: "https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?auto=format&fit=crop&q=80&w=400" },
      webcast: "https://www.youtube.com/watch?v=OnoNITE-CLg"
    }
  },
  {
    id: "starlink-12-1",
    name: "Starlink Group 12-1",
    date_utc: "2026-05-30T14:45:00.000Z",
    details: "SpaceX Falcon 9 will launch a batch of Starlink v2-mini satellites into low Earth orbit to expand internet coverage.",
    rocket_name: "Falcon 9 Block 5",
    launchpad_name: "SLC-40, Cape Canaveral",
    upcoming: true,
    flight_number: 162,
    links: {
      patch: { large: "https://images.unsplash.com/photo-1517976487492-5750f3195933?auto=format&fit=crop&q=80&w=400" },
      webcast: "https://www.youtube.com/watch?v=F3G8Dclg8eI"
    }
  }
];

export const FALLBACK_NEWS = [
  {
    id: 1,
    title: "SpaceX Super Heavy Catch on Second Attempt Redefines Flight Reuse",
    news_site: "NASA Spaceflight",
    published_at: "2026-05-15T12:00:00.000Z",
    summary: "SpaceX has successfully caught the Super Heavy booster back at the launch tower during Flight 5, marking a monumental milestone in rocket reuse and fast-cycle flights.",
    url: "https://www.spacex.com/"
  },
  {
    id: 2,
    title: "Falcon Heavy Launches GOES-U Next-Gen Weather Satellite",
    news_site: "Spaceflight Now",
    published_at: "2026-05-12T18:30:00.000Z",
    summary: "A SpaceX Falcon Heavy successfully placed NOAA's advanced weather satellite into geostationary transfer orbit with dual booster recovery at Kennedy Space Center.",
    url: "https://www.spacex.com/"
  },
  {
    id: 3,
    title: "Starlink Surpasses 8 Million Subscribers Globally, Falcon 9 Fleet Expands",
    news_site: "Teslarati",
    published_at: "2026-05-09T09:15:00.000Z",
    summary: "With weekly Falcon launches, SpaceX’s satellite internet constellation Starlink now connects over eight million active users across more than 85 countries.",
    url: "https://www.spacex.com/"
  },
  {
    id: 4,
    title: "Starship Flight 6 Operational Targets Approved by FAA for Summer Launch",
    news_site: "Aerospace America",
    published_at: "2026-05-08T14:20:00.000Z",
    summary: "Federal regulators have cleared flight envelopes for Flight 6, approving operational plans for dual ship-tower recoveries and higher orbital thermal test loads.",
    url: "https://www.spacex.com/"
  },
  {
    id: 5,
    title: "Crew-10 Dragon Spacecraft Prepares for Long-Duration Orbital Run",
    news_site: "Space News",
    published_at: "2026-05-06T11:45:00.000Z",
    summary: "Engineers have concluded vacuum chamber leak checks on the Dragon capsule assigned to USCV-10, readying the spacecraft for cargo staging at LC-39A.",
    url: "https://www.spacex.com/"
  },
  {
    id: 6,
    title: "SpaceX Secures Landmark Deep Space Launch Contract for Uranus Probe",
    news_site: "NASA Mission Reports",
    published_at: "2026-05-04T16:10:00.000Z",
    summary: "A triple-core Falcon Heavy configuration will launch NASA's priority planetary probe on an outer solar system gravity-assist trajectory scheduled in late 2026.",
    url: "https://www.spacex.com/"
  },
  {
    id: 7,
    title: "Next-Gen Raptor 3 Engine Achieves Record Combustion Chamber Pressure",
    news_site: "TechCrunch Science",
    published_at: "2026-05-02T08:30:00.000Z",
    summary: "SpaceX's simplified build Raptor 3 rocket engine has logged over 350 bar peak chamber pressure on the McGregor test stand while improving thrust performance.",
    url: "https://www.spacex.com/"
  },
  {
    id: 8,
    title: "Reusable Fairings Set New Turnaround Record of 21 Days for Starlink Flights",
    news_site: "Booster Analytics",
    published_at: "2026-04-30T10:05:00.000Z",
    summary: "Fast cycle cleaning and structural inspections on recovery vessel Bob have enabled fairing halves to fly twice within one month, saving millions in manufacturing.",
    url: "https://www.spacex.com/"
  },
  {
    id: 9,
    title: "Robotic Arm Mechazilla Upgrade Slated to Accelerate Launch Operations",
    news_site: "Spaceflight Now",
    published_at: "2026-04-28T15:00:00.000Z",
    summary: "Installation of shock dampening cylinders and wider hinge bearings at Starbase OLP-1 will reduce turnaround time between Starship orbital stacking operations.",
    url: "https://www.spacex.com/"
  }
];
